import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Details from './details';
import List from './list';
import Source from "./source";

export default function Home() {
    const [config, setConfig] = useState(null);
    const [dataflow, setDataflow] = useState(null);

    const handleNewConfig = (newConfig) => {
        setConfig({...newConfig, ssl: true});
    };

    const handleDataflowSelection = (dataflow) => {
        setDataflow(dataflow);
    }

    const handleOnGoBackClick = () => {
        setDataflow(null);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Materialize</title>
                <meta name="description" content="Generated by Materialize" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {config === null && <Source editable config={config || {}} onConfigChange={handleNewConfig} />}
                {config && !dataflow && <List config={config} onDataflowSelected={handleDataflowSelection} />}
                {config && dataflow && (
                    <button
                        className="absolute left-0 top-0 m-10"
                        type="button"
                        onClick={handleOnGoBackClick}
                    >Go Back</button>
                )}
                {config && dataflow && <Details config={config} dataflow={dataflow} />}
            </main>

            <footer className={styles.footer}>
                <a
                    // href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/logo192.png" alt="Materialize Logo" width={16} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
